services:
  - type: web
    name: pdf-ocr-extraction
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    staticPublishPath: static
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        value: 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
      - key: OPENAI_API_BASE
        value: https://api.groq.com/openai/v1
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: OPENAI_MODEL_NAME
        value: llama3-8b-8192
