services:
  - type: web
    name: pdf-ocr-extraction
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p ~/.streamlit
      echo "[server]" > ~/.streamlit/config.toml
      echo "headless = true" >> ~/.streamlit/config.toml
      echo "port = \$PORT" >> ~/.streamlit/config.toml
      echo "enableCORS = false" >> ~/.streamlit/config.toml
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    staticPublishPath: static  # 👈 This is the missing line!
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
