services:
  - type: web
    name: pdf-ocr-extraction
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p ~/.streamlit
      echo "\
      [server]\n\
      headless = true\n\
      port = \$PORT\n\
      enableCORS = false\n\
      " > ~/.streamlit/config.toml
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
